-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 23:52:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema house
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema house
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `house` DEFAULT CHARACTER SET utf8 ;
USE `house` ;

-- -----------------------------------------------------
-- Table `house`.`usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house`.`usr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `house`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_num` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `usr_id` INT NOT NULL,
  UNIQUE INDEX `phone_num_UNIQUE` (`phone_num` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `usr_id_idx` (`usr_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `usr_id`
    FOREIGN KEY (`usr_id`)
    REFERENCES `house`.`usr` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `house`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `name` TEXT NOT NULL,
  `usr_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE,
  INDEX `usr_id_idx` (`usr_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`usr_id`)
    REFERENCES `house`.`usr` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `house`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house`.`data` (
  `property_id` INT NOT NULL,
  `electricity` INT NOT NULL,
  `data` INT NOT NULL,
  INDEX `property_id_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `property_id`
    FOREIGN KEY (`property_id`)
    REFERENCES `house`.`property` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
